data-source:
  user-management:
    url: jdbc:sqlserver://192.168.100.190:1433;databaseName=SMEE_UserManagement
    username: sa
    password: Newton35
    initial-size: 5
    min-idle: 5
    max-idle: 20
    max-active: 20
    test-on-borrow: true
    validation-query: SELECT 1
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver



custom:
  mail: 
    from: GIS_Strategy_COE@gap.com
  sso:
    url: https://onelogonqa.gap.com/pf/adapter2adapter.ping?SpSessionAuthnAdapterId=pclOT&TargetResource=http://localhost:9001/smee/
  oauth-token:
    url: http://gateway:secretId@localhost:8120/smee/oauth/token
